apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotd
  template:
    metadata:
      labels:
        app: gotd
    spec:
      containers:
      - name: gotd
        image: gcr.io/t-collective-432006-r7/gotd:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m" 
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        envFrom:
        - configMapRef:
            name: gotd-config
        ports:
        - containerPort: 80  
