apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotd
  template:
    metadata:
      labels:
        app: gotd
    spec:
      containers:
      - name: gotd
        image: gcr.io/t-collective-432006-r7/gotd:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2000m"   # 2 vCPU
            memory: "4Gi"
            ephemeral-storage: "20Gi"
          limits:
            cpu: "4000m"   # 4 vCPU = ~4 Gbps
            memory: "8Gi"
            ephemeral-storage: "40Gi"
        envFrom:
        - configMapRef:
            name: gotd-config
        ports:
        - containerPort: 80  
